services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/node/workspace:delegated
    working_dir: /home/node/workspace
    tty: true
    user: node
    ports:
      - 3000:3000
