services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:delegated
    working_dir: /workspace
    tty: true
    user: node
    ports:
      - 3000:3000
